feat: add controllers
RomanAtreides/java-shareit-ra-hw pull request #1
Opened 2022-09-16 19:14 UTC by RomanAtreides

2022-09-16 21:50 UTC, Fleaman777 requested changes

2022-09-16 21:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestHeader(value = "X-Sharer-User-Id", required = false) Long userId) {
X-Sharer-User-Id - можно вынести в константу

2022-09-16 21:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +    private Long generateId() {
приватный-вспомогательный метод хорошо бы разместить после публичных, 
так при беглом просмотре класса, будет легче понять какое апи у этого класса

аналагично в User..Storage

2022-09-16 21:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +        }
хороший кандидат на то, что бы сделать этот foreach через stream

2022-09-16 21:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +            }
этот тоже можно переделать на стрим формат

2022-09-16 21:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/utility/Validator.java
> +public class Validator {
здорово, что валидацию решил вынести в отдельный компонент - грамотное разделение ответственности

2022-09-16 21:50 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                .collect(Collectors.toList());
в целом, логику перемапливания в Dto объект можно перенести в сервис, 

решение остается за тобой, т.к. оба варианта имеют место быть

2022-09-17 10:22 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +            @RequestHeader(value = "X-Sharer-User-Id", required = false) Long userId) {
Исправил

2022-09-17 10:27 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +    private Long generateId() {
Исправил

2022-09-17 10:28 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/utility/Validator.java
> +public class Validator {
Спасибо)

2022-09-17 10:57 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                .collect(Collectors.toList());
Я где-то прочитал, что обычно это происходит на presentation layer, да и мне такой вариант больше нравится, поэтому если ты не против оставлю как есть

2022-09-17 11:15 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +        }
Исправил

2022-09-17 11:29 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +            }
Исправил

2022-09-18 12:59 UTC, Fleaman777 requested changes

2022-09-18 12:59 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final String headerNameContainsOwnerId = "X-Sharer-User-Id";
это полноценная константа, 
поэтому можно назвать в верхнем региcтре и добавить ключевое слово static

2022-09-18 12:59 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +        });
стало получше, 
но можно еще немного проапрегйлить и сделать так: 

```
return items.values().stream()
.filter(item.getOwner().equals(userId))
.collect(Collectors.toList())
```

2022-09-18 12:59 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +            }
здесь можно переделать подобным образом как в перд. комменте, 
только например, логику сравнения которая в ифах, можно вынести в отдельный приватный метод(someMethodName),  
тогда у нас в методе filter будет что-то типа такого: 
filter(this::someMethodName) 

someMethodName будет возвращать boolean  и принимать item 
ну и нужно будет поменять немного название :)

2022-09-18 20:07 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +        });
Исправил

2022-09-18 20:16 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final String headerNameContainsOwnerId = "X-Sharer-User-Id";
Исправил

2022-09-18 21:11 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +            }
Исправил, но не получилось с помощью ссылки на метод сделать, потому что в него кроме item ещё и переменную finalText надо передавать

2022-09-19 06:54 UTC, Fleaman777 approved these changes

2022-09-19 17:41 UTC, merged