feat: add item requests
RomanAtreides/java-shareit-ra-hw pull request #3
Opened 2022-11-21 20:12 UTC by RomanAtreides

Add item requests and tests

2022-11-22 17:41 UTC, Fleaman777 requested changes

2022-11-22 17:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
если значение параметра name совпадает с названием аргумента, то параметр name в аннотации можно не указывать 

относится ко всем похожим местам

2022-11-22 17:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    bookings = bookingRepository.findUserBookings(userId, pageable);
попробуй логику if(isOwner)... сделать не через if-else, а через тернарный оператор, 
длолжно получится покомпактней

2022-11-22 17:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +                itemRequest
если нужно просетать большое количество полей(больше 5) в 1 объект, то более практично использовать билдер

2022-11-22 17:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    List<ItemDto> items;
поле должно быть private

2022-11-22 17:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/utility/FromSizeRequest.java
> +public class FromSizeRequest extends PageRequest {
хороший общий класс

2022-11-22 17:41 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", userId))
здесь в тестах X-Sharer-User-Id - тоже можно было бы вынести в константу

2022-11-22 17:41 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>  public class BookingController {
классы контроллеров, репозиториев лучше переместить в собственные пакеты, так в будущем будет проще ориентироваться в структуре проекта, 

соответственно, то же самое, нужно будет сделать и с тестовыми классами

2022-11-22 17:41 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    }
хороший setUp метод, выполняются все необходимые просечивания

2022-11-23 18:13 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
Исправил

2022-11-23 18:18 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                    bookings = bookingRepository.findUserBookings(userId, pageable);
Исправил. Так намного красивее и компактнее. Спасибо за подсказку

2022-11-23 18:29 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    List<ItemDto> items;
Точно!) Исправил

2022-11-23 18:30 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/utility/FromSizeRequest.java
> +public class FromSizeRequest extends PageRequest {
Спасибо!

2022-11-23 18:47 UTC, RomanAtreides commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    }
Спасибо!

2022-11-23 19:08 UTC, RomanAtreides commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", userId))
Сделал

2022-11-23 19:33 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>  public class BookingController {
Сделал

2022-11-23 21:13 UTC, RomanAtreides commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +                itemRequest
Исправил

2022-11-25 09:25 UTC, Fleaman777 approved these changes

2022-11-26 09:33 UTC, merged