feat: add docker
RomanAtreides/java-shareit-ra-hw pull request #4
Opened 2022-12-04 11:14 UTC by RomanAtreides

2022-12-05 17:13 UTC, Fleaman777 requested changes

2022-12-05 17:13 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private static ResponseEntity<Object> prepareGatewayResponse(ResponseEntity<Object> response) {
вспомогательные private методы лучше размещать, в конце, после публичных и protected, 
так, при беглом просмотре, будет чуть понятней, какое апи у класса,

2022-12-05 17:13 UTC, Fleaman777 commented on server/Dockerfile
> +FROM amazoncorretto:11-alpine-jdk
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,

то же относится и к просто Dockerfile

2022-12-05 17:13 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            @Validated({Create.class}) @RequestBody CommentShortDto commentShortDto,
здорово, что для валидации используешь аннотации, так код всопринимается лучше

2022-12-05 17:13 UTC, Fleaman777 commented on docker-compose.yml
> +      - POSTGRES_USER=shareit_user
сейчас получается, что значения переменных окружения, используются те, которые указаны в application.properties, а не те, которые в docker-compose

например в application.properties ,
можно использовать такую конструкцию: spring.datasource.username=${POSTGRES_USER:shareit_user}
она означает, что если, в докер-компосе не просетать переменную POSTGRES_USER, то будет использоваться дефлотное значение shareit_user

2022-12-05 18:16 UTC, RomanAtreides commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private static ResponseEntity<Object> prepareGatewayResponse(ResponseEntity<Object> response) {
Исправил

2022-12-05 18:25 UTC, RomanAtreides commented on gateway/src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            @Validated({Create.class}) @RequestBody CommentShortDto commentShortDto,
Спасибо!

2022-12-05 18:25 UTC, RomanAtreides commented on server/Dockerfile
> +FROM amazoncorretto:11-alpine-jdk
Спасибо!

2022-12-05 19:09 UTC, RomanAtreides commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private static ResponseEntity<Object> prepareGatewayResponse(ResponseEntity<Object> response) {
А вообще это не я, это IDEA)) Когда нажимаю Ctrl+Alt+L этот private static метод сам убегает вверх

2022-12-05 19:12 UTC, RomanAtreides commented on docker-compose.yml
> +      - POSTGRES_USER=shareit_user
Исправил

2022-12-06 15:38 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private static ResponseEntity<Object> prepareGatewayResponse(ResponseEntity<Object> response) {
хм, интресно)

2022-12-06 15:40 UTC, Fleaman777 approved these changes

2022-12-06 19:03 UTC, merged